package defaults

class Constants {
	
	
	// Authentiication par environnement d'apprentissage
	public static final String  PrimarytraceEnv = "PrimarytraceEnv";
	public static final String PrimarytraceEnvProfil = "EnvProfil"
	public static final String PrimarytraceEnvSignature = "EnvSignature"
	// Authentification KD 
	//Authentification MD 
	//Authentification KD amd MD 
	public static final Trace_ProfilKDMD = "Trace_ProfilKDMD"
	public static final Trace_SignatureKDMD = "Trace_SignatureKDMD"
	
	
	public static final String  Primarytrace = "Primarytrace";
	public static final String  modelprimary = "modelprimary"
	public static final String  Trace_Signature = "Trace_Signature"
	public static final String  Trace_Profil = "Trace_Profil"
	public static final String  Trace_ProfilClassic = "Trace_ProfilClassic"
	public static final String  Trace_ProfilDynamic = "Trace_ProfilDynamic"
	public static final String  Trace_Profile_Keystroke = "Trace_Profile_Keystroke"
	public static final String Trace_Signature_Keystroke = "Trace_Signature_Keystroke"
	public static final String Trace_Profile_Mouse = "Trace_Profile_Mouse"
	public static final String Trace_Signature_Mouse = "Trace_Signature_Mouse"
	public static final String Trace_MPR = "Trace_MPR"
	public static final String Trace_MPPRRRP = "Trace_MPPRRRP"
	public static final String Trace_Click = "Trace_Click"
	public static final String Trace_Dclick = "Trace_Dclick"
	public static final String Trace_FsaMoveSegment = "Trace_FsaMoveSegment"
	public static final String Trace_SparqlMoveSegment ="Trace_SparqlMoveSegment"
	public static final String Trace_FsaMoveAcion = "Trace_FsaMoveAcion"
	public static final String Trace_SparqlMoveAction = "Trace_SparqlMoveAction"
	public static final String Trace_filtreDD = "Trace_filtreDD"
	public static final String Trace_fussionDD ="Trace_fussionDD"
	public static final String Trace_MouseFSADD = "Trace_MouseFSADD"
	public static final String Trace_MDD = "Trace_MDD"
	public static final String Trace_MBPR ="Trace_MBPR"
	public static final String TraceProfileMouseLimit = "TraceProfileMouseLimit"
	public static final String Trace_MMS = "Trace_MMS"
	public static final String type_K_PR = "K_PR"
	public static final String type_K_MPR = "K_MPR"
	public static final String type_K_PP = "K_PP"
	public static final String type_K_RR = "K_RR"
	public static final String type_K_RP = "K_RP"
	public static final String type_M_MS = "M_MS"
	public static final String type_M_DD = "M_DD"
	public static final String type_M_BPR = "M_BPR"
	public static final String type_M_MBPR = "M_MBPR"
	public static final String att_keySource ="keySource"
	public static final String att_mean ="mean"
	public static final String att_deviation = "deviation"
	public static final String att_time = "time"
	public static final String att_keyDestination = "keyDestination"
	public static final String att_direction = "direction"
	public static final String att_meanTime = "meanTime"
	public static final String att_deviationTime = "deviationTime"
	public static final String att_timeElapsed = "timeElapsed"
	public static final String att_meanacceleration ="meanacceleration"
	public static final String att_deviationacceleration ="deviationacceleration"
	public static final String att_acceleration = "acceleration"
	public static final String att_meanSpeed ="meanSpeed"
	public static final String att_deviationSpeed ="deviationSpeed"
	public static final String att_actualSpeed = "actualSpeed"
	public static final String att_meancurveAcceleration = "meancurveAcceleration"
	public static final String att_deviationcurveAcceleration = "deviationcurveAcceleration"
	public static final String att_curveAcceleration = "curveAcceleration"
	public static final String att_meancurveLength = "meancurveLength"
	public static final String att_deviationcurveLength = "deviationcurveLength"
	public static final String att_curveLength = "curveLength"
	public static final String att_meantravelledDistance = "meantravelledDistance"
	public static final String att_deviationtravelledDistance ="deviationtravelledDistance"
	public static final String att_travelledDistance = "travelledDistance"
	public static final String att_duration ="duration"
	public static final Trace_MouseDD = "Trace_MouseDD"
	public static final Trace_SignatureDynamic = "Trace_SignatureDynamic"
	public static final Trace_SignatureClassic = "Trace_SignatureClassic"
}
